### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [runvnc/json-update#4]
@runvnc 

Hey there, very good project!

Is there any plans in adding the standard Promises A+ instead of callbacks? It would be amazing if one wants to run the code returning values and throwing errors in the same execution structure. It will also account for the future await/async generators in ES2016.

For example:

```javascript
update('data.json', { test: 'value x' }).then(function(obj) {
  console.log(obj);
}).catch(function(err) {
  console.error(err);
});
```

You can also use [bluebird](https://www.npmjs.com/package/bluebird) and the [`.promisify` function](http://bluebirdjs.com/docs/api/promise.promisify.html) which automatically changes node-like callback to promises!

Usually what people do is:

* Have passed a callback in the last argument? Use node callbacks.
* Haven't passed a callback in the last argument? Use Promises A+.

Thoughts?

**Comment by runvnc** [comment]
Good idea, I may add promises at some point.

**Comment by FagnerMartinsBrack** [comment]
> I may add promises at some point.

Looking forward to it ^^

**Comment by runvnc** [comment]
I added promises and async/await support.
